# Generated by Django 2.2.17 on 2021-02-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=20, null=True)),
                ('country_name', models.CharField(blank=True, max_length=50, null=True)),
                ('region_name', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=8, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
